
title: Hexq
description: Свалка мыслей
logo: logo.svg

remote_theme: just-the-docs/just-the-docs
search_enabled: false

# markdown render engine.
markdown:         kramdown

syntax_highlighter_style: colorful

owner:
   name: Vladimir S Kravchenko
   email: kvover@gmail.com
   github: HexQuant
markdown: kramdown
kramdown:
   math_engine: mathjax
github:
   is_project_page: false
 
tracker:
   google_analytics: "G-J9W2DLNM0T"
#theme: jekyll-theme-hacker
